### ISSUE TITLE
A 'declare' modifier cannot be used in an already ambient context.

### ISSUE THREAD

**Issue by max-mykhailenko** [ferdikoomen/webpack-typings-for-css#140]
**Describe the bug**
Your example generate next error
![image](https://user-images.githubusercontent.com/1213198/81471848-ad176880-91fc-11ea-9e16-ef47adc5ca0c.png)

**Comment by ferdikoomen** [comment]
Let me have a look max! What editor and typescript version are you using?

**Comment by ferdikoomen** [comment]
Question: did you name this something**.d.ts** ?

**Comment by max-mykhailenko** [comment]
I am using Sublime (Build 3210) with official Typescript plugin (latest version). Typescript version 3.8.3. 

Working module definition for me looks like 
```
declare module '*.css' {
  const classes: { [key: string]: string };
  export default classes;
}
```

And with module definition above I get next type definition 

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1213198/81510275-476cce80-9319-11ea-981a-48460a1f4c4c.png">

**Comment by ferdikoomen** [comment]
Hi Max,

I tried a simple example and i'm not seeing any issues :( If you have some time then add me on Skype: ferdikoomen. We can have a quick sync later this week (if you have time). We can add a small note in the readme.md file for sublime users.

**Comment by max-mykhailenko** [comment]
@ferdikoomen never mind, it's just `d.ts` files, I tested with my team my definition on different laptops and environments and it works. Close issue if somebody will have similar problem.
